# NAIVE BAYES CLASSIFIER

**Reading the Dataset**

In [1]:
import pandas as pd

df = pd.read_excel('DATASET.xlsx',index_col ='Example')
df

        ALT Bar Fri Hun   Pat Price Rain Res     Type       Est Target Wait
Example
X1        T   F   F   T  Some   $$$    F   T   French   0 to 10           T
X2        T   F   F   T  Full     $    F   F     Thai  30 to 60           F
X3        F   T   F   F  Some     $    F   F   Burger   0 to 10           T
X4        T   F   T   T  Full     $    F   F     Thai  10 to 30           T
X5        T   F   T   F  Full   $$$    F   T   French      > 60           F
X6        F   T   F   T  Some    $$    T   T  Italian   0 to 10           T
X7        F   T   F   F  None     $    T   F   Burger   0 to 10           F
X8        F   F   F   T  Some    $$    T   T     Thai   0 to 10           T
X9        F   T   T   F  Full     $    T   F   Burger      > 60           F
X10       T   T   T   T  Full   $$$    F   T  Italian  10 to 30           F
X11       F   F   F   F  None     $    F   F     Thai   0 to 10           F
X12       T   T   T   T  Full     $    F   F   Burger  30 to 60           T

**Function for Generating the Probability Table**

In [2]:
import numpy as np

def get_prob_table(df,label):
    prob_table = {}
    values,counts = np.unique(df[label],return_counts = True)
    idx = {values[i]:i for i in range(len(values))}
    for col in df.columns[:-1]:
        table = {}
        for x,y in zip(values,counts):
            dff = df.where(df[label] == x).dropna()
            val,cnt = np.unique(dff[col],return_counts = True)
            for a,b in zip(val,cnt):
                if a not in table:
                    table[a] = np.ones(len(values))*0.001 #Setting the minimum probability to 10e-3
                table[a][idx[x]] = b/y
        table[col] = values
        prob_table[col] = pd.DataFrame(table).set_index(col).T
    prob = {}
    for i in range(len(values)):
        prob[values[i]] = counts[i]/len(df)
    return prob_table,pd.DataFrame(prob,index = ['Probability'])

**Function to Classify a Data Point**

In [3]:
def classify(prob_table,prob,X):
    probab = {}
    for x in prob:
        pr = prob[x]['Probability']
        for var in X:
            m = prob_table[var]
            pr = pr*m[x][X[var]]
        probab[x] = pr
    return max(prob,key = probab.get)

***PROBABILITY TABLE***

In [4]:
label = 'Target Wait'
prob_table, prob = get_prob_table(df,label)
for x in prob_table:
    print('Probability Table of',x)
    print(prob_table[x],'\n')
print('Probability of values in the Target Column')
print(prob)

Probability Table of ALT
ALT    F    T
F    0.5  0.5
T    0.5  0.5

Probability Table of Bar
Bar    F    T
F    0.5  0.5
T    0.5  0.5

Probability Table of Fri
Fri    F         T
F    0.5  0.666667
T    0.5  0.333333

Probability Table of Hun
Hun         F         T
F    0.666667  0.166667
T    0.333333  0.833333

Probability Table of Pat
Pat          F         T
Full  0.666667  0.333333
None  0.333333  0.001000
Some  0.001000  0.666667

Probability Table of Price
Price         F         T
$      0.666667  0.500000
$$$    0.333333  0.166667
$$     0.001000  0.333333

Probability Table of Rain
Rain         F         T
F     0.666667  0.666667
T     0.333333  0.333333

Probability Table of Res
Res         F    T
F    0.666667  0.5
T    0.333333  0.5

Probability Table of Type
Type            F         T
Burger   0.333333  0.333333
French   0.166667  0.166667
Italian  0.166667  0.166667
Thai     0.333333  0.333333

Probability Table of Est
Est              F         T
0 to 10   0.333333  0.666667
10 to 30  0.166667  0.166667
30 to 60  0.166667  0.166667
> 60      0.333333  0.001000

Probability of values in the Target Column
               F    T
Probability  0.5  0.5

***CLASSIFICATION***

In [5]:
X = {'ALT': 'T', 
     'Bar': 'T', 
     'Fri': 'F', 
     'Hun': 'T', 
     'Pat': 'Some', 
     'Price': '$$$', 
     'Rain': 'T', 
     'Res': 'T', 
     'Type': 'Italian', 
     'Est': '> 60'}

In [6]:
a = classify(prob_table,prob,X)
print(f'The given Data Point is classified as {label} = {a}')

The given Data Point is classified as Target Wait = T